/*****************************************************************************************
                        Zanobia - fingerprinting data analysis software
Copyright (C) 2020 Usama S Erawab <alrawab@hotmail.com> Libya
This program is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 2 of the License, or
(at your option) any later version.
This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
GNU General Public License for more details.
You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA
************************************************************************************************/
package zanobia2;

import java.awt.Image;
import java.io.File;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author alrawab
 */
public class MainWindow extends javax.swing.JFrame {

    /**
     * Creates new form MainWindow
     */
    
    ImageIcon pic3= new ImageIcon(getClass().getClassLoader().getResource("vb.png"));
    ImageIcon pic4= new ImageIcon(getClass().getClassLoader().getResource("04.png"));
    
    public MainWindow() {
        initComponents();
         Image img3=pic3.getImage();
        Image imgscale3=img3.getScaledInstance(jLabel3.getWidth(), jLabel3.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon scaledicon3=new ImageIcon(imgscale3);
          jLabel3.setIcon(scaledicon3);
           
          Image img4=pic4.getImage();
        Image imgscale4=img4.getScaledInstance(jLabel4.getWidth(), jLabel4.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon scaledicon4=new ImageIcon(imgscale4);
          jLabel4.setIcon(scaledicon4);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ZANOBIA");

        jTable1.setAutoCreateRowSorter(true);
        jTable1.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jTable1.setForeground(new java.awt.Color(0, 51, 204));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"CSF1PO_gen", "TAGA", "5q33.1", null, null, null, null, null, null, null, null},
                {"D3S1358_gen", "[TCTG] [TCTA]", "3p21.31	", null, null, null, null, null, null, null, null},
                {"D5S818_gen", "AGAT", "5q23.2", null, null, null, null, null, null, null, null},
                {"D7S820_gen", "GATA", "7q21.11", null, null, null, null, null, null, null, null},
                {"D8S1179_gen", "TCTA", "8q24.13", null, null, null, null, null, null, null, null},
                {"D13S317_gen", "TATC", "13q31.1", null, null, null, null, null, null, null, null},
                {"D16S539_gen", "GATA", "16q24.1", null, null, null, null, null, null, null, null},
                {"D18S51_gen", "AGAA", "18q21.33", null, null, null, null, null, null, null, null},
                {"D21S11_gen", "[TCTA] [TCTG]", "21q21.1", null, null, null, null, null, null, null, null},
                {"FGA_gen", "[CTTT] [CCTT]", "4q31.3", null, null, null, null, null, null, null, null},
                {"TH01_gen", "AATG", "11p15.5", null, null, null, null, null, null, null, null},
                {"TPOX_gen", "TGAA", "2p25.3", null, null, null, null, null, null, null, null},
                {"VWA_gen", "[TCTG] [TCTA]", "12p13.31", null, null, null, null, null, null, null, null}
            },
            new String [] {
                "CODIS Gene", "Repeat Motif", "Chromosomal Locations", "Sample 1_A.1", "Sample 1_A.2", "Sample 2_A.1", "Sample 2_A.2", "Sample 3_A.1", "Sample 3_A.2", "Sample 4_A.1", "Sample 4_A.2"
            }
        ));
        jTable1.setOpaque(false);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTable1MousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel2.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 102, 204));
        jLabel2.setText("Please Select Identity");

        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 204));
        jLabel1.setText("Combined DNA Index System (CODIS) Gene");

        jComboBox1.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jComboBox1.setForeground(new java.awt.Color(0, 51, 255));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CSF1PO_gen", "D3S1358_gen", "D5S818_gen", "D7S820_gen", "D8S1179_gen", "D13S317_gen", "D16S539_gen", "D18S51_gen", "D21S11_gen", "FGA_gen", "TH01_gen", "TPOX_gen", "VWA_gen" }));
        jComboBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox1ItemStateChanged(evt);
            }
        });

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jRadioButton1.setForeground(new java.awt.Color(0, 0, 204));
        jRadioButton1.setSelected(true);
        jRadioButton1.setText("Identity One");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jRadioButton2.setForeground(new java.awt.Color(0, 51, 255));
        jRadioButton2.setText("Identity Two");

        buttonGroup1.add(jRadioButton3);
        jRadioButton3.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jRadioButton3.setForeground(new java.awt.Color(0, 51, 255));
        jRadioButton3.setText("Identity Three");

        jButton1.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jButton1.setText("Select Fasta File");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jButton2.setText("Clear Selected row");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton4);
        jRadioButton4.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jRadioButton4.setForeground(new java.awt.Color(0, 51, 255));
        jRadioButton4.setText("Identity Four");

        jLabel3.setText("jLabel1");

        jLabel4.setText("jLabel2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(334, 334, 334)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 456, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(225, 225, 225)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(64, 64, 64))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(254, 254, 254)
                        .addComponent(jRadioButton1)
                        .addGap(18, 18, 18)
                        .addComponent(jRadioButton2)
                        .addGap(35, 35, 35)
                        .addComponent(jRadioButton3)
                        .addGap(18, 18, 18)
                        .addComponent(jRadioButton4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 218, Short.MAX_VALUE)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(168, 168, 168)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(66, 66, 66)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(376, 376, 376))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jRadioButton2)
                        .addComponent(jRadioButton3)
                        .addComponent(jRadioButton4)
                        .addComponent(jRadioButton1))
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTable1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MousePressed
 int rowIndex = jTable1.getSelectedRow();
        // JOptionPane.showMessageDialog(null,  String.valueOf(rowIndex));
        jComboBox1.setSelectedIndex(rowIndex);        // TODO add your handling code here:
    }//GEN-LAST:event_jTable1MousePressed

    private void jComboBox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox1ItemStateChanged
int index = jComboBox1.getSelectedIndex() ;
   //     System.out.println(index);
jTable1.setRowSelectionInterval(index, index);
    }//GEN-LAST:event_jComboBox1ItemStateChanged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

       //   File file=new File("C:\\demo\\D3S1358.fasta");
     //  String a =CSF1PO.Get_ALLEL_SEQ().get(16).toString();
        //System.out.println(a);  
        //System.out.println(CSF1PO.RepeatUnit);  
      
     //   System.out.println(FGA.Get_ALLEL_SEQ().get(50.2));
     // String aa=  ReadFasta_1.ParseFasta("C:\\demo\\d3.fasta");
     //   System.out.println( D3S1358.Find_Allel_NO(aa));
        
        
        
JFileChooser jf = new JFileChooser();
FileNameExtensionFilter filter = new FileNameExtensionFilter("FASTA FILES", "fa", "fasta");
jf.setFileFilter(filter); 
jf.setDialogTitle("Please Specify Fasta File to Process");  
jf.setCurrentDirectory(new File(System.getProperty("user.home")));
int result = jf.showOpenDialog(this);
if (result == JFileChooser.APPROVE_OPTION) {
    File selectedFile = jf.getSelectedFile();
      ReadFasta rf=new ReadFasta();
     //System.out.println(selectedFile.getAbsolutePath());
  //  System.out.println(rf.ParseFasta(selectedFile.getAbsolutePath()).length());
List<String> seq=rf.ParseFasta(selectedFile.getAbsolutePath());
    //****************System.out.println(seq.get(1));
    //***************System.out.println(D3S1358.Find_Allel_NO(seq.get(1)));
   //  System.out.println("------------------------");
     //System.out.println(seq.get(0).length());// size());   //get(0));
    //  System.out.println(seq.get(1));
   // if (seq.size()!=2)
 // {
 // return;
 // }
   
 if (seq.get(1).length()==0&& seq.get(0).length()==0)
 {
     return;
 }
 int a=jComboBox1.getSelectedIndex();
 switch (a) {
  case 0:
    double  x1= CSF1PO.Find_Allel_NO(seq.get(1) );
      System.out.println(x1);
      double  y1=0;
      if(seq.get(0).length()>0)
    y1= CSF1PO.Find_Allel_NO(seq.get(0) );
      if(jRadioButton1.isSelected()){
      jTable1.setValueAt(x1, 0, 3);
      jTable1.setValueAt(y1, 0, 4);
      }
      if(jRadioButton2.isSelected()){
      jTable1.setValueAt(x1, 0, 5);
      jTable1.setValueAt(y1, 0, 6);
      }
      if(jRadioButton3.isSelected()){
      jTable1.setValueAt(x1, 0, 7);
      jTable1.setValueAt(y1, 0, 8);
      }
      if(jRadioButton4.isSelected()){
      jTable1.setValueAt(x1, 0, 9);
      jTable1.setValueAt(y1, 0, 10);
      }
      break;
      //--------------end of case 0
      case 1:
    double  x2= D3S1358.Find_Allel_NO(seq.get(1) );
      System.out.println(D3S1358.Find_Allel_NO(seq.get(1)));
      System.out.println(D3S1358.Find_Allel_NO(seq.get(0)));
      double  y2=0;
      if(seq.get(0).length()>0)
    y2= D3S1358.Find_Allel_NO(seq.get(0) );
      if(jRadioButton1.isSelected()){
      jTable1.setValueAt(x2, 1, 3);
      jTable1.setValueAt(y2, 1, 4);
      }
      if(jRadioButton2.isSelected()){
      jTable1.setValueAt(x2, 1, 5);
      jTable1.setValueAt(y2, 1, 6);
      }
      if(jRadioButton3.isSelected()){
      jTable1.setValueAt(x2, 1, 7);
      jTable1.setValueAt(y2, 1, 8);
      }
      if(jRadioButton4.isSelected()){
      jTable1.setValueAt(x2, 1, 9);
      jTable1.setValueAt(y2, 1, 10);
      }
      break;
      case 2:
    double  x3= D5S818.Find_Allel_NO(seq.get(1) );
      
      double  y3=0;
      if(seq.get(0).length()>0)
    y3= D5S818.Find_Allel_NO(seq.get(0) );
      if(jRadioButton1.isSelected()){
      jTable1.setValueAt(x3, 2, 3);
      jTable1.setValueAt(y3, 2, 4);
      }
      if(jRadioButton2.isSelected()){
      jTable1.setValueAt(x3, 2, 5);
      jTable1.setValueAt(y3, 2, 6);
      }
      if(jRadioButton3.isSelected()){
      jTable1.setValueAt(x3, 2, 7);
      jTable1.setValueAt(y3, 2, 8);
      }
      if(jRadioButton4.isSelected()){
      jTable1.setValueAt(x3, 2, 9);
      jTable1.setValueAt(y3, 2, 10);
      }
      break;
      case 3:
    double  x4= D7S820.Find_Allel_NO(seq.get(1) );
      
      double  y4=0;
      if(seq.get(0).length()>0)
    y4= D7S820.Find_Allel_NO(seq.get(0) );
      if(jRadioButton1.isSelected()){
      jTable1.setValueAt(x4, 3, 3);
      jTable1.setValueAt(y4, 3, 4);
      }
      if(jRadioButton2.isSelected()){
      jTable1.setValueAt(x4, 3, 5);
      jTable1.setValueAt(y4, 3, 6);
      }
      if(jRadioButton3.isSelected()){
      jTable1.setValueAt(x4, 3, 7);
      jTable1.setValueAt(y4, 3, 8);
      }
      if(jRadioButton4.isSelected()){
      jTable1.setValueAt(x4, 3, 9);
      jTable1.setValueAt(y4, 3, 10);
      }
      break;      
      
      case 4:
    double  x5= D8S1179.Find_Allel_NO(seq.get(1) );
      
      double  y5=0;
      if(seq.get(0).length()>0)
    y5= D8S1179.Find_Allel_NO(seq.get(0) );
      if(jRadioButton1.isSelected()){
      jTable1.setValueAt(x5, 4, 3);
      jTable1.setValueAt(y5, 4, 4);
      }
      if(jRadioButton2.isSelected()){
         
      jTable1.setValueAt(x5, 4, 5);
      jTable1.setValueAt(y5, 4, 6);
      }
      if(jRadioButton3.isSelected()){
      jTable1.setValueAt(x5, 4, 7);
      jTable1.setValueAt(y5, 4, 8);
      }
      if(jRadioButton4.isSelected()){
      jTable1.setValueAt(x5, 4, 9);
      jTable1.setValueAt(y5, 4, 10);
      }
      break;      
      
       case 5:
    double  x6= D13S317.Find_Allel_NO(seq.get(1) );
      
      double  y6=0;
      if(seq.get(0).length()>0)
    y6= D13S317.Find_Allel_NO(seq.get(0) );
      if(jRadioButton1.isSelected()){
      jTable1.setValueAt(x6, 5, 3);
      jTable1.setValueAt(y6, 5, 4);
      }
      if(jRadioButton2.isSelected()){
      jTable1.setValueAt(x6, 5, 5);
      jTable1.setValueAt(y6, 5, 6);
      }
      if(jRadioButton3.isSelected()){
      jTable1.setValueAt(x6, 5, 7);
      jTable1.setValueAt(y6, 5, 8);
      }
      if(jRadioButton4.isSelected()){
      jTable1.setValueAt(x6, 5, 9);
      jTable1.setValueAt(y6, 5, 10);
      }
      break;      
       case 6:
    double  x7= D16S539.Find_Allel_NO(seq.get(1) );
      
      double  y7=0;
      if(seq.get(0).length()>0)
    y7= D16S539.Find_Allel_NO(seq.get(0) );
      if(jRadioButton1.isSelected()){
      jTable1.setValueAt(x7, 6, 3);
      jTable1.setValueAt(y7, 6, 4);
      }
      if(jRadioButton2.isSelected()){
      jTable1.setValueAt(x7, 6, 5);
      jTable1.setValueAt(y7, 6, 6);
      }
      if(jRadioButton3.isSelected()){
      jTable1.setValueAt(x7, 6, 7);
      jTable1.setValueAt(y7, 6, 8);
      }
      if(jRadioButton4.isSelected()){
      jTable1.setValueAt(x7, 6, 9);
      jTable1.setValueAt(y7, 6, 10);
      }
      break;      
       case 7:
    double  x8= D18S51.Find_Allel_NO(seq.get(1) );
      
      double  y8=0;
      if(seq.get(0).length()>0)
    y8= D18S51.Find_Allel_NO(seq.get(0) );
      if(jRadioButton1.isSelected()){
      jTable1.setValueAt(x8, 7, 3);
      jTable1.setValueAt(y8, 7, 4);
      }
      if(jRadioButton2.isSelected()){
      jTable1.setValueAt(x8, 7, 5);
      jTable1.setValueAt(y8, 7, 6);
      }
      if(jRadioButton3.isSelected()){
      jTable1.setValueAt(x8, 7, 7);
      jTable1.setValueAt(y8, 7, 8);
      }
      if(jRadioButton4.isSelected()){
      jTable1.setValueAt(x8, 7, 9);
      jTable1.setValueAt(y8, 7, 10);
      }
      break;
      case 8:
    double  x9= D21S11.Find_Allel_NO(seq.get(1) );
      
      double  y9=0;
      if(seq.get(0).length()>0)
    y9= D21S11.Find_Allel_NO(seq.get(0) );
      if(jRadioButton1.isSelected()){
      jTable1.setValueAt(x9, 8, 3);
      jTable1.setValueAt(y9, 8, 4);
      }
      if(jRadioButton2.isSelected()){
      jTable1.setValueAt(x9, 8, 5);
      jTable1.setValueAt(y9, 8, 6);
      }
      if(jRadioButton3.isSelected()){
      jTable1.setValueAt(x9, 8, 7);
      jTable1.setValueAt(y9, 8, 8);
      }
      if(jRadioButton4.isSelected()){
      jTable1.setValueAt(x9, 8, 9);
      jTable1.setValueAt(y9, 8, 10);
      }
      break;
      
      case 9:
    double  x10= FGA.Find_Allel_NO(seq.get(1) );
      
      double  y10=0;
      if(seq.get(0).length()>0)
    y10= FGA.Find_Allel_NO(seq.get(0) );
      if(jRadioButton1.isSelected()){
      jTable1.setValueAt(x10, 9, 3);
      jTable1.setValueAt(y10, 9, 4);
      }
      if(jRadioButton2.isSelected()){
      jTable1.setValueAt(x10, 9, 5);
      jTable1.setValueAt(y10, 9, 6);
      }
      if(jRadioButton3.isSelected()){
      jTable1.setValueAt(x10, 9, 7);
      jTable1.setValueAt(y10, 9, 8);
      }
      if(jRadioButton4.isSelected()){
      jTable1.setValueAt(x10, 9, 9);
      jTable1.setValueAt(y10, 9, 10);
      }
      break;
      
       case 10:
    double  x11= TH01.Find_Allel_NO(seq.get(1) );
      
      double  y11=0;
      if(seq.get(0).length()>0)
    y11= TH01.Find_Allel_NO(seq.get(0) );
      if(jRadioButton1.isSelected()){
      jTable1.setValueAt(x11, 10, 3);
      jTable1.setValueAt(y11, 10, 4);
      }
      if(jRadioButton2.isSelected()){
      jTable1.setValueAt(x11, 10, 5);
      jTable1.setValueAt(y11, 10, 6);
      }
      if(jRadioButton3.isSelected()){
      jTable1.setValueAt(x11, 10, 7);
      jTable1.setValueAt(y11, 10, 8);
      }
      if(jRadioButton4.isSelected()){
      jTable1.setValueAt(x11, 10, 9);
      jTable1.setValueAt(y11, 10, 10);
      }
      break;
      
      case 11:
    double  x12= TPOX.Find_Allel_NO(seq.get(1) );
      
      double  y12=0;
      if(seq.get(0).length()>0)
    y12= TPOX.Find_Allel_NO(seq.get(0) );
      if(jRadioButton1.isSelected()){
      jTable1.setValueAt(x12, 11, 3);
      jTable1.setValueAt(y12, 11, 4);
      }
      if(jRadioButton2.isSelected()){
      jTable1.setValueAt(x12, 11, 5);
      jTable1.setValueAt(y12, 11, 6);
      }
      if(jRadioButton3.isSelected()){
      jTable1.setValueAt(x12, 11, 7);
      jTable1.setValueAt(y12, 11, 8);
      }
      if(jRadioButton4.isSelected()){
      jTable1.setValueAt(x12, 11, 9);
      jTable1.setValueAt(y12, 11, 10);
      }
      break;
      case 12:
    double  x13= VWA.Find_Allel_NO(seq.get(1) );
      
      double  y13=0;
      if(seq.get(0).length()>0)
    y13= VWA.Find_Allel_NO(seq.get(0) );
      if(jRadioButton1.isSelected()){
      jTable1.setValueAt(x13, 12, 3);
      jTable1.setValueAt(y13, 12, 4);
      }
      if(jRadioButton2.isSelected()){
      jTable1.setValueAt(x13, 12, 5);
      jTable1.setValueAt(y13, 12, 6);
      }
      if(jRadioButton3.isSelected()){
      jTable1.setValueAt(x13, 12, 7);
      jTable1.setValueAt(y13, 12, 8);
      }
      if(jRadioButton4.isSelected()){
      jTable1.setValueAt(x13, 12, 9);
      jTable1.setValueAt(y13, 12, 10);
      }
      break;
      
 }  
 //D5S818.Find_Allel_NO(seq)
  //--------------end of case1    
   
 
  
  
  
   /*
   switch (a) {
  case 0:
    //System.out.println(xx);
      int x1=bruteforce(seq.get(1),"TAGA");//allel 1
      int y1=bruteforce(seq.get(0),"TAGA");//allel 2
      
    if(jRadioButton1.isSelected()){
      jTable1.setValueAt(x1, 0, 3);
      jTable1.setValueAt(y1, 0, 4);
    }
    if(jRadioButton2.isSelected()){
    jTable1.setValueAt(x1, 0, 5);
     jTable1.setValueAt(y1, 0, 6);
    }
    if(jRadioButton3.isSelected()){
    jTable1.setValueAt(x1, 0, 7);
     jTable1.setValueAt(y1, 0, 8);
    }
    break;
    //========================================
    case 1:
    //System.out.println(xx);
      int x2=bruteforce(seq.get(1),"TCTG");
      int y2=bruteforce(seq.get(0),"TCTG");
    if(jRadioButton1.isSelected()){
     jTable1.setValueAt(x2, 1, 3);
      jTable1.setValueAt(y2, 1, 4);
    }
    if(jRadioButton2.isSelected()){
      //table.setValueAt(x2, 1, 4);
       jTable1.setValueAt(x2, 1, 5);
      jTable1.setValueAt(y2, 1, 6);
    }
     if(jRadioButton3.isSelected()){
      //table.setValueAt(x2, 1, 4);
       jTable1.setValueAt(x2, 1, 7);
      jTable1.setValueAt(y2, 1, 8);
    }
    break;
    //=============================================
     case 2:
    //System.out.println(xx);
      int x3=bruteforce(seq.get(1),"AGAT");
      int y3=bruteforce(seq.get(0),"AGAT");
    if(jRadioButton1.isSelected()){
     // table.setValueAt(x3, 2, 3);
      jTable1.setValueAt(x3, 2, 3);
      jTable1.setValueAt(y3, 2, 4);
    }
    if(jRadioButton2.isSelected()){
      //table.setValueAt(x3, 2, 4);
      jTable1.setValueAt(x3, 2, 5);
      jTable1.setValueAt(y3, 2, 6);
    }
    if(jRadioButton3.isSelected()){
      //table.setValueAt(x3, 2, 4);
      jTable1.setValueAt(x3, 2, 7);
      jTable1.setValueAt(y3, 2, 8);
    }
    break;
    //------------4---------------
    case 3:
    //System.out.println(xx);
      int x4=bruteforce(seq.get(1),"GATA");
      int y4=bruteforce(seq.get(0),"GATA");
    if(jRadioButton1.isSelected()){
      //table.setValueAt(x4, 3, 3);
       jTable1.setValueAt(x4, 3, 3);
      jTable1.setValueAt(y4, 3, 4);
    }
    if(jRadioButton2.isSelected()){
      //table.setValueAt(x4, 3, 4);
       jTable1.setValueAt(x4, 3, 5);
      jTable1.setValueAt(y4, 3, 6);
    }
     if(jRadioButton3.isSelected()){
      //table.setValueAt(x4, 3, 4);
       jTable1.setValueAt(x4, 3, 7);
      jTable1.setValueAt(y4, 3, 8);
    }
    break;
    //----------------5-------------------
     case 4:
    //System.out.println(xx);
      int x5=bruteforce(seq.get(1),"TCTG");
      int y5=bruteforce(seq.get(0),"TCTG");
    if(jRadioButton1.isSelected()){
      //table.setValueAt(x5, 4, 3);
       jTable1.setValueAt(x5, 4, 3);
      jTable1.setValueAt(y5, 4, 4);
    }
    if(jRadioButton2.isSelected()){
      //table.setValueAt(x5, 4, 4);
       jTable1.setValueAt(x5, 4, 5);
      jTable1.setValueAt(y5, 4, 6);
    }
    if(jRadioButton3.isSelected()){
      //table.setValueAt(x5, 4, 4);
       jTable1.setValueAt(x5, 4, 7);
      jTable1.setValueAt(y5, 4, 8);
    }
    break;
    //----------------6-------------------
     case 5:
    //System.out.println(xx);
      int x6=bruteforce(seq.get(1),"TATC");
        int y6=bruteforce(seq.get(0),"TATC");
    if(jRadioButton1.isSelected()){
      jTable1.setValueAt(x6, 5, 3);
      jTable1.setValueAt(y6, 5, 4);
    }
    if(jRadioButton2.isSelected()){
       jTable1.setValueAt(x6, 5, 5);
      jTable1.setValueAt(y6, 5, 6);
    }
    if(jRadioButton3.isSelected()){
       jTable1.setValueAt(x6, 5, 7);
      jTable1.setValueAt(y6, 5, 8);
    }
    break;
    //----------------7-------------------
     case 6:
    //System.out.println(xx);
      int x7=bruteforce(seq.get(1),"GATA");
      int y7=bruteforce(seq.get(0),"GATA");
    if(jRadioButton1.isSelected()){
       jTable1.setValueAt(x7, 6, 3);
       jTable1.setValueAt(y7, 6, 4);
    }
    if(jRadioButton2.isSelected()){
      jTable1.setValueAt(x7, 6, 5);
       jTable1.setValueAt(y7, 6, 6);
    }
    if(jRadioButton3.isSelected()){
      jTable1.setValueAt(x7, 6, 7);
       jTable1.setValueAt(y7, 6, 8);
    }
    break;
    //----------------8-------------------
     case 7:
    //System.out.println(xx);
      int x8=bruteforce(seq.get(1),"AGAA");
      int y8=bruteforce(seq.get(0),"AGAA");
    if(jRadioButton1.isSelected()){
      jTable1.setValueAt(x8, 7, 3);
      jTable1.setValueAt(y8, 7, 4);
    }
    if(jRadioButton2.isSelected()){
      jTable1.setValueAt(x8, 7, 5);
      jTable1.setValueAt(y8, 7, 6);
    }
    if(jRadioButton3.isSelected()){
      jTable1.setValueAt(x8, 7, 7);
      jTable1.setValueAt(y8, 7, 8);
    }
    break;
     //----------------9-------------------
     case 8:
    //System.out.println(xx);
      int x9=bruteforce(seq.get(1),"TCTA");
      int y9=bruteforce(seq.get(0),"TCTA");
    if(jRadioButton1.isSelected()){
      jTable1.setValueAt(x9, 8, 3);
      jTable1.setValueAt(y9, 8, 4);
    }
    if(jRadioButton2.isSelected()){
       jTable1.setValueAt(x9, 8, 5);
      jTable1.setValueAt(y9, 8, 6);
    }
    if(jRadioButton3.isSelected()){
       jTable1.setValueAt(x9, 8, 7);
      jTable1.setValueAt(y9, 8, 8);
    }
    break;
     //----------------10-------------------
     case 9:
    //System.out.println(xx);
      int x10=bruteforce(seq.get(1),"CTTT");
      int y10=bruteforce(seq.get(0),"CTTT");
    if(jRadioButton1.isSelected()){
     jTable1.setValueAt(x10, 9, 3);
      jTable1.setValueAt(y10, 9, 4);
    }
    if(jRadioButton2.isSelected()){
      jTable1.setValueAt(x10, 9, 5);
      jTable1.setValueAt(y10, 9, 6);
    }
     if(jRadioButton3.isSelected()){
      jTable1.setValueAt(x10, 9, 7);
      jTable1.setValueAt(y10, 9, 8);
    }
    break;
    //------------------------11----
    case 10:
    //System.out.println(xx);
      int x11=bruteforce(seq.get(1),"AATG");
      int y11=bruteforce(seq.get(0),"AATG");
    if(jRadioButton1.isSelected()){
      jTable1.setValueAt(x11, 10, 3);
       jTable1.setValueAt(y11, 10, 4);
    }
    if(jRadioButton2.isSelected()){
      jTable1.setValueAt(x11, 10, 5);
       jTable1.setValueAt(y11, 10, 6);
    }
    if(jRadioButton3.isSelected()){
      jTable1.setValueAt(x11, 10, 7);
       jTable1.setValueAt(y11, 10, 8);
    }
    break;
    //------------------------12----
    case 11:
    //System.out.println(xx);
      int x12=bruteforce(seq.get(1),"TGAA");
      int y12=bruteforce(seq.get(0),"TGAA");
    if(jRadioButton1.isSelected()){
     jTable1.setValueAt(x12, 11, 3);
     jTable1.setValueAt(y12, 11, 4);
    }
    if(jRadioButton2.isSelected()){
      jTable1.setValueAt(x12, 11, 5);
     jTable1.setValueAt(y12, 11, 6);
    }
    if(jRadioButton3.isSelected()){
      jTable1.setValueAt(x12, 11, 7);
     jTable1.setValueAt(y12, 11, 8);
    }
    break;
     //------------------------13----
    case 12:
    //System.out.println(xx);
      int x13=bruteforce(seq.get(1),"TCTG");
      int y13=bruteforce(seq.get(0),"TCTG");
    if(jRadioButton1.isSelected()){
      jTable1.setValueAt(x13, 12, 3);
      jTable1.setValueAt(y13, 12, 4);
    }
    if(jRadioButton2.isSelected()){
      jTable1.setValueAt(x13, 12, 5);
      jTable1.setValueAt(y13, 12, 6);
    }
    if(jRadioButton2.isSelected()){
      jTable1.setValueAt(x13, 12, 7);
      jTable1.setValueAt(y13, 12, 8);
    }
    break;
   }//--------------------
    */
}
        // TODO add your handling code here:
      
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
     //   int x= jTable1.getSelectedColumns();
     try
     {
      DefaultTableModel md=(DefaultTableModel)jTable1.getModel();
      int x= jTable1.getSelectedColumn();
        System.out.println(x);
     }
     catch(Exception ex){}
    }//GEN-LAST:event_jButton2ActionPerformed
  /**
     * @param args the command line arguments
     */
    
    public  int bruteforce(String input,String pattern){
       int output = 0;
    for (int i = 0; i <= input.length() - pattern.length(); i++) {
        boolean ok = true;
        for (int k = 0; k < pattern.length(); k++) {
            if(input.charAt(i + k) != pattern.charAt(k)) {
                ok = false;
                break;
            }
        }
        if(ok) output++;
    }
    return output;
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
